description: ""
triggers:
  - type: opened
    device_id: *
    entity_id: *
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id: *