description: ""
triggers:
  - trigger: state
    entity_id:
      - light.aqara_smart_wall_switch
    from: "off"
    to: "on"
conditions: []
actions:
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.ganglicht_aan
mode: single
