description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.aqara_door_and_window_sensor_p2_door
    from: "off"
    to: "on"
conditions:
  - condition: or
    conditions:
      - condition: zone
        entity_id: device_tracker.person1
        zone: zone.onderwerg_naar_huis
      - condition: state
        entity_id: person.kim
        state: Onderwerg naar huis
actions:
  - choose:
      - conditions:
          - condition: time
            after: "10:00:00"
            before: "20:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
        sequence:
          - action: media_player.volume_set
            metadata: {}
            data:
              volume_level: 0.08
            target:
              device_id: *
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: light.aqara_smart_wall_switch_light_1
          - action: media_player.play_media
            target:
              entity_id: media_player.huiskamer
            data:
              media_content_type: spotify://playlist
              enqueue: play
              media_content_id: >-
              link_to_your_spotify_playlist
      - conditions:
          - condition: time
            after: "20:00:00"
            before: "10:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
              - sat
              - sun
          - condition: state
            entity_id: light.mini_smart_wi_fi_plug
            state: "off"
        sequence:
          - action: light.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: light.aqara_smart_wall_switch_light_1
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: automation.wasmachine_status_naar_klaar
                state: "on"
              - type: is_not_open
                condition: device
                device_id: *
                entity_id: *
                domain: binary_sensor
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              rgb_color:
                - 241
                - 10
                - 10
              brightness_pct: 100
            target:
              entity_id: light.smart_rgbtw_bulb
mode: single